### ISSUE TITLE
C# question for Milliorn

### ISSUE THREAD

**Issue by trialsofnewcastle** [trialsofnewcastle/Trials-Of-Newcastle#164]
Is there an existing plugin that I could sit in the repo that would unlock data moving from Discord to the server?

(ie. Through a combo of `nwnx_chat` and `nwnx_webhook` we can pipe info from server to Discord, I am looking for a tool to do the reverse process.)

**Comment by milliorn** [comment]
AFAIK there is no tool to go from Discord to NwN because no one has made it and there wouldn't be anything remotely generic enough like in Github to do such a thing out of the box. To get this functionality it will have to be built an it probably be more than a trivial job. 

In order for something to go from Discord to the game it would also require something patched into .net nwn andor nwnxee as well. I don't think .net alone can do this without nwnxee in its current state. Maybe in the future. That be a question for Urothis/Jorteck.
